"""create_ratings_table

Revision ID: 398b9e6c1d11
Revises: 6070ebfc211f
Create Date: 2026-06-19 15:54:42.510034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398b9e6c1d11'
down_revision: Union[str, Sequence[str], None] = '6070ebfc211f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ride_id', sa.String(), nullable=False),
    sa.Column('passenger_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'passenger_id', name='uq_rating_ride_passenger')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
