"""add_custom_note_to_preferences

Revision ID: bb5574cad9b0
Revises: c1a14dcaac27
Create Date: 2026-06-19 11:17:43.596648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5574cad9b0'
down_revision: Union[str, Sequence[str], None] = 'c1a14dcaac27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ride_id'), table_name='bookings')
    op.add_column('driver_preferences', sa.Column('custom_note', sa.String(), nullable=True))
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_constraint(op.f('rides_driver_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_driver_id_fkey'), 'rides', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.drop_column('driver_preferences', 'custom_note')
    op.create_index(op.f('ix_bookings_ride_id'), 'bookings', ['ride_id'], unique=False)
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    # ### end Alembic commands ###
